### ISSUE TITLE
Large module sprite clipping visual bug

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event_horizon#20]
Within the ship constructor, when zoomed in, lower portions of sprites of very large modules can clip as shown below
![unknown](https://user-images.githubusercontent.com/61762578/187157115-92ff2ec0-0976-4106-9d00-dc1939634226.png)
:

**Comment by juh9870** [comment]
This may or may not change with constructor rework, I will not try to fix it before that
