### ISSUE TITLE
Widespread barrel hierarchy bug

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event_horizon#28]
Lots of ships across the entire vanilla database (probably most ships) have their barrels configured in the wrong order by default as seen in the below example:

![image](https://user-images.githubusercontent.com/61762578/187449198-7ee3feff-ab15-444a-9031-28c9747caf5f.png)
![image](https://user-images.githubusercontent.com/61762578/187449748-268aae93-bded-4efe-9f6c-5b7d624561cb.png)
![image](https://user-images.githubusercontent.com/61762578/187450343-868d878f-a4b0-4bc9-9776-40e37c14aa3e.png)
![image](https://user-images.githubusercontent.com/61762578/187451622-b9f708e6-afd5-4dbf-a3e9-b4f47624bb7b.png)

The list goes on.
This includes most titans and regular ships with more than 1 weapon barrel.

**Comment by juh9870** [comment]
I won't fix these issues personally, but I'd accept a PR that fixes them.
For the name of the commit with fixes, please use `fix(gameplay): fixed barrels issues on vanilla ships`.
#27 should also be included here

**Comment by juh9870** [comment]
Fixed in acfe588ccb96c82cd5e2de3ec25bcde38cd140a2, please open a new issue if you find new ones.
