### ISSUE TITLE
The option "Show Damage Numbers" is broken

### ISSUE THREAD

**Issue by SIVLER7405** [PavelZinchenko/event_horizon#3]
Option still shows up damage numbers even when turned off.

![image](https://user-images.githubusercontent.com/96327594/187034812-01ddb2fe-145e-49f6-a2cc-e39e775e7a33.png)
![image](https://user-images.githubusercontent.com/96327594/187034837-41d08398-7f4b-4237-92c6-f64b38513524.png)

**Comment by juh9870** [comment]
Fixed in b92693a818a9acb450474f91a9dacf682f7dbdc2
