### ISSUE TITLE
Devices unused options bug

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event_horizon#31]
#### Accelerator: 
- [x] power - boost multiplier
- [x]  lifetime - limit for the activation time (as in cloaking)
#### BrakeDevice:
- ~~activation type, like in energy shield and stealth~~ This would work better as a separate device
#### ClonningCenter:
- [x] power - damage and health multiplier
#### DecoyDevice:
- [x]  size - decoy health
#### Detonator:
- [x] offset - move blast, as in frontal shield
#### Fortification:
- [x] power - resists multiplier
- [x] lifetime - limit for the activation time (as in cloaking)
#### FrontalShield:
- [x] lifetime - limit for the activation time (as in cloaking)
#### InfinityStone:
- [x] power - amount of ship health and energy, that given when using (in %)
#### RepairBot:
- ~~cooldown - delay after activation before healing~~ - cooldown is already used
- ~~lifetime - healing time before next cooldown~~ - implemented lifetime the same as other devices
#### Teleporter:
- [x] offset - parameter as range, but with more abilities (like teleport backwards or sideways)
#### ToxicWasteDevice:
- [x] offset - move cloud, as in frontal shield
#### Autopilot:
- ~~activation type, like in energy shield and stealth~~ This would work better as a separate device

**Comment by juh9870** [comment]
This is not a bug report but rather missing features, I will look into them

**Comment by juh9870** [comment]
Struck trough options are to be added to EH:CE
