### ISSUE TITLE
Problems with messages in quests

### ISSUE THREAD

**Issue by Kipyatochkov** [PavelZinchenko/event_horizon#33]
If the text in the message is long or there are many displayed actions in the message, then the message is displayed incorrectly (for example, the text in the actions disappears). Possible solution to this problem: adding scrolling text and actions in the message

**Comment by juh9870** [comment]
Partially fixed in 314ba035e7daf3ab0155cf93c86d4fd06dc4d6e5
Scrolling wasn't added, but I will accept a PR if someone manages to do it properly
