### ISSUE TITLE
Is it possible if I try to build a new scene with a giant Black Hole inside, which will destroy any ship near by and makes every bullets in the scene derail?

### ISSUE THREAD

**Issue by ULE7** [PavelZinchenko/event_horizon#39]
Is it possible if I try to build a new scene with a giant Black Hole inside, which will destroy any ship near by and makes every bullets in the scene derail?

**Comment by juh9870** [comment]
Yes, it is possible. But for such questions, please join an official discord server instead of creating issues https://discordapp.com/invite/yFFvF7m
