### ISSUE TITLE
Workshop cost value overflow 

### ISSUE THREAD

**Issue by ViviX12** [PavelZinchenko/event_horizon#46]
if a ship is large and costly enough, the workshop cost of upgraded versions can overflow and give money to the player instead of subtracting

**Comment by juh9870** [comment]
What do you suggest as a fix?
The most direct way would be to rework currencies to use `long` instead of `int` but that would require far too much rework to be kept in vanilla. I will definitely do that in EH:CE, but vanilla requires a different fix

**Comment by ViviX12** [comment]
without a rework, perhaps cap the maximum cost at the integer limit, so that it can't overflow (instead going back right to the cap)

**Comment by juh9870** [comment]
But then it would be uncraftable, cuz player can't effectively get to Int limit without overflowing back into negative

**Comment by ViviX12** [comment]
I can't see a solution that wouldn't trade drawbacks

**Comment by juh9870** [comment]
Okay, so looks like this will have to wait for EH:CE, I can cap crafting price at 2b credits in a meanwhile

**Comment by ViviX12** [comment]
sounds sensible for the time being
