### ISSUE TITLE
Quick battle asteroid bug

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event_horizon#5]
When the player enters a quick battle from the main menu while a savegame exists and is loaded, the asteroids in the quick battle will deal increased collision damage based on the player's distance from home in the loaded campaign savefile. If one has a save loaded with a very high LY value, asteroids in quick battle can potentially OHKO some weaker ships.

**Comment by juh9870** [comment]
As stupid as this sounds, fixing this is non-trivial and requires reworking quite a bit of stuff. As an alternative, I may just remove asteroids from QB

**Comment by juh9870** [comment]
Okay, for now I will just remove asteroids from QB
