### ISSUE TITLE
Planetary exploration issues

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event_horizon#55]
-Game refuses to spawn outpost on planets, if mod misses vanilla id components (Lack of ships with drone category seems to cause this too) 
-Outpost builds doesn't depend on its layout at all (tested with empty layout)
-Outpost turrets can only use C slot weapons
-Hives are hardoced to use 16 ID faction instead of proper ID within exploration file

**Comment by juh9870** [comment]
I fixed faction always using 16, but others will have to wait. For now, I can only provide a list of IDs that must be present
