### ISSUE TITLE
Velocity in beams triggers autotargetting prediction of ship position

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event_horizon#69]
As result of this beams manage to miss with 360 degree aimiming

**Comment by juh9870** [comment]
Are there any actual purpose for beam with velocity?

**Comment by Zen9890** [comment]
Beams with velocity can get increased lifetime with range boost and vice versa

**Comment by juh9870** [comment]
~~@Zen9890 please check https://github.com/PavelZinchenko/event_horizon/tree/weapon_platform_fix branch and tell if it fixes the issue for you~~
I managed to reproduce the issue and fix it
