### ISSUE TITLE
Trailing | in description leads to confusing behaviour

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event_horizon#73]
![image](https://user-images.githubusercontent.com/62694017/190846771-2eb3a4d9-6480-4a10-9396-2df2cd1a4d61.png)
I hidden range value here because it used only for AI, but doing so added this blank space between stats and description

**Comment by Zen9890** [comment]
That was mine side misstake

**Comment by juh9870** [comment]
Works aa intended, but I should remove trailing `|` symbol to prevent this issue in a future
