### ISSUE TITLE
InitialPosition field doesnt work in obsolete ammo

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event_horizon#74]
Title

**Comment by juh9870** [comment]
Does it not work when you fire it from weapon, or from carrier?

**Comment by Zen9890** [comment]
It doesnt work in both situations

**Comment by juh9870** [comment]
Okay, here is the issue - almost every vanilla gun have some default values in there, so adding functionality will break weapons in almost all present mods
