### ISSUE TITLE
Impulse field in obsolete ammo doesnt work with IonBeam type ammo

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event_horizon#75]
Recoil with IonBeam does work, but impulse doesnt apply to enemies on hit

**Comment by juh9870** [comment]
Currently, only a very limited set of ammunition apply impact on hit. Changing this requires a bit of discussion and experimentation
https://github.com/PavelZinchenko/event_horizon/blob/82737378aab429dd312a32780e342c6f6c83c53e/Starship/Assets/Scripts/Combat/Factory/Bullets/AmmunitionClassExtensions.cs#L112-L125

**Comment by juh9870** [comment]
I created a new branch, where every obsolete ammunition that isn't AOE, laser or DOT can apply impulse, and I need someone to check how all obsolete ammunition types work with Impulse.

Branch: https://github.com/PavelZinchenko/event_horizon/tree/obsolete-impact-test
