### ISSUE TITLE
Cloak bug

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event_horizon#8]
If you kill a ship with a cloaking device, the next enemy won't be able to use cloak properly. If you use cloak and you get killed, next ship with cloak you select will have malfunctioning cloak.

**Comment by juh9870** [comment]
Can't reproduce. Please provide the database with a situation where a ship with cloak can be killed

**Comment by juh9870** [comment]
This is like treating symptoms while ignoring the root cause. I will try to fix #36 instead
